### ISSUE TITLE
Require vs Import

### ISSUE THREAD

**Issue by mitchellslager** [mitchellslager/portfolio-react#3]
What is the difference between the following methods, are they even comparable?

````javascript
import React from 'react';
// and
var React = require('react');
````

I've learned that import is a new feature of ES6 but I'm having a hard time finding more information.

**Comment by blurrah** [comment]
Require is also called CommonJS, the standard for Node to import modules. Import is the new ES6 standard of importing modules.

Browserify enables you to use CommonJS in the browser. Babel can transpile import into require.

**Comment by mitchellslager** [comment]
Thanks!
