### ISSUE TITLE
Distribute components into separate files and folders

### ISSUE THREAD

**Issue by mitchellslager** [mitchellslager/portfolio-react#4]
For a better project architecture all components should be in their own file

**Comment by mitchellslager** [comment]
<b>Update</b>
By creating a component in a separate file and exporting the module this can be easily achieved.
The component file should look similar to this:
````javascript
/** @jsx React.DOM */
var React = require('react');

var Header = React.createClass({
  render: function() {
    return (
      <header>
        // Header stuff
      </header>
    );
  }
});

module.exports = Header;
````
To use this component in another file all I have to do is:
````javascript
var Header = require('./path-to-component/Header.js');
// and to display the component...
<Header />
````

**Comment by mitchellslager** [comment]
<b>Update 2</b>
All components have been successfully distributed except the Header component.

The Header component includes the main menu. Which works with these links:
````javascript
<ul>
  <li><Link to="app">Work</Link></li>
  <li><Link to="about">About</Link></li>
  <li><Link to="contact">Contact</Link></li>
</ul>
````
I get the following console error:
Uncaught ReferenceError: Link is not defined

**Comment by blurrah** [comment]
var Link = require('react-router').Link or so.

**Comment by mitchellslager** [comment]
Thanks for your suggestion!

I tried the following code in my `Header.js` file:
````javascript
/** @jsx React.DOM */
var React = require('react');

// Tried all of these individually:
var Link = require('react-router').link;
var Link = require('react-router').Link;
var Link = Router.Link;

var Header = React.createClass({
  render: function() {
    return (
      <header>
        <ul>
          <li><Link to="app">Work</Link></li>
          <li><Link to="about">About</Link></li>
          <li><Link to="contact">Contact</Link></li>
        </ul>
      </header>
    );
  }
});

module.exports = Header;
````
I required `Header.js` in my main file `app.js` which contains the Routes and stuff.
But it still does not work, same error as before.

**Comment by mitchellslager** [comment]
Got it working by using the following code:
````javascript
var Router = require('react-router');
var Link = Router.Link;
````
There was something wrong with my Gulp setup which made me have to reset everything when changing some javascript. Will look into that now.
